Repository ProyectoIntegrador2018/salud360, pull requests merged in 2019-03, with the labels that each got.

#83 Hernan´s fix
  .gitignore
  app/views/sesions/edit.html.erb
  log/development.log
Labels: Priority, Sprint 1, bug

#85 Done
  app/views/pacientes_pages/mis_sesiones.html.erb
Labels: Sprint 1, bug

#104 ve, adds missing diet indicator to my patients page in nutriologist user
  app/views/nutriologo_pages/mis_pacientes.html.erb
Labels: enhancement

#105 ve, adds indicator when session date has passed
  app/views/nutriologo_pages/mis_sesiones.html.erb
Labels: enhancement

#108 Enhancement/ Add patient name to sesions/edit
  app/controllers/sesions_controller.rb
  app/views/sesions/edit.html.erb
Labels: enhancement
