Repository ProyectoIntegrador2018/salud360, pull requests merged in 2019-04, with the labels that each got.

#122 Solves offset in expired sessions indicator
  app/views/nutriologo_pages/mis_sesiones.html.erb
Labels: Sprint 3, bug

#128 Fix[migration]: Update schema version to last migration
  db/schema.rb
Labels: bug

#127 Update README.md
  README.md
Labels: Chore

#126 Create DEPLOYMENT.md file
  DEPLOYMENT.md
Labels: Chore

#125 Update issue templates
  .github/ISSUE_TEMPLATE/bug-file.md
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/maintenance-request.md
Labels: Chore
